import type { Problem } from "../types";

export const autoResearch: Problem[] = [
  {
    id: "research-grid-random-bayesian",
    track: "autoresearch",
    title: "Grid vs Random vs Bayesian Search",
    difficulty: "core",
    tags: ["HPO", "random search", "bayesian optimization"],
    source: "Bergstra & Bengio, Random Search for Hyper-Parameter Optimization (2012)",
    prompt:
      "Compare grid search, random search, and Bayesian optimization for hyperparameter tuning. Why does random search beat grid search in high dimensions, and when would you reach for Bayesian optimization instead?",
    solution:
      "**The three families.** Given a hyperparameter space, you must decide *which* configurations to evaluate.\n\n- **Grid search** evaluates the full Cartesian product: $k$ hyperparameters with $n$ values each costs $n^k$ trials — exponential in dimension. It also tests only $n$ *distinct* values along any single axis no matter how large the total budget.\n- **Random search** samples each configuration independently from the (possibly continuous) space. With a budget of $B$ trials it explores $B$ *distinct* values along **every** axis.\n- **Bayesian optimization** fits a probabilistic surrogate to past results and sequentially picks the most promising next point.\n\n**Why random beats grid (Bergstra & Bengio, 2012).** Real objectives have **low effective dimensionality**: only a few hyperparameters (e.g. learning rate) strongly move the loss; the rest barely matter. Grid search wastes its budget re-testing the *same* few values of the important knob while exhaustively sweeping the irrelevant ones. A $10\\times10$ grid spends 100 trials but samples each axis at only 10 places; random search with 100 trials samples the important axis at ~100 distinct places.\n\nThe probability that at least one of $B$ random draws lands in the top-$p$ fraction of the important dimension is\n$$P = 1 - (1-p)^{B}.$$\nTo cover the top 5% region ($p=0.05$) with 95% confidence you need $1-0.95^{B}\\ge 0.95$, i.e. **$B \\approx 60$** trials — *independent of the total dimensionality*. Grid search needs exponentially more.\n\n| Method | Distinct values / axis | Parallel? | Sample-efficient? | Scales to many dims |\n|---|---|---|---|---|\n| Grid | $n$ | fully | no | no ($n^{k}$) |\n| Random | $B$ | fully | medium | yes |\n| Bayesian | $B$ | limited (sequential) | high | degrades in high-$d$ |\n\n**When to use which.** Random search is the strong, embarrassingly-parallel baseline and the right default for a first sweep. Reach for **Bayesian optimization** when each trial is expensive and you can afford sequential evaluation — it uses every result to inform the next query and needs far fewer trials. Grid is justified only for 1–2 hyperparameters or when you specifically want an interpretable, evenly-spaced map of the landscape.",
    keyInsight:
      "Only a few hyperparameters matter, so grid wastes trials re-testing irrelevant axes; random search samples B distinct values on every axis and needs only ~60 draws to hit the top-5% region regardless of dimension.",
  },
  {
    id: "research-successive-halving-hyperband-asha",
    track: "autoresearch",
    title: "Successive Halving, Hyperband & ASHA",
    difficulty: "hard",
    tags: ["HPO", "bandits", "early stopping"],
    source: "Li et al., Hyperband (2018); Li et al., ASHA (2020)",
    prompt:
      "Explain Successive Halving, how Hyperband builds on it, and what ASHA changes. When does aggressive early stopping fail?",
    solution:
      "When each configuration is trained *iteratively* (over epochs, data, or trees), you can **early-stop** bad configs cheaply and pour that compute into promising ones — a pure-exploration **multi-armed bandit**.\n\n**Successive Halving (SHA).** Start $n$ configurations with a small resource $r$ (say 1 epoch). Evaluate, keep the top $1/\\eta$, multiply their resource by $\\eta$, and repeat until one remains. With reduction factor $\\eta$ (default 3–4), rung $i$ trains $n\\eta^{-i}$ configs at resource $r\\eta^{i}$, so each rung costs roughly the same total budget — you spend **exponentially more resource on exponentially fewer, better** configs.\n\n**The $n$-vs-$B/n$ dilemma.** For a fixed total budget $B$, many configs ($n$ large) means broad exploration but little resource each, so early rankings are noisy and you may kill a slow-starting winner. Few configs means each is judged faithfully but you explore less. SHA forces you to guess this tradeoff up front.\n\n**Hyperband** removes the guess: it runs SHA as an inner loop across several **brackets**, each with a different $(n, r)$ starting point — from many-configs/tiny-resource (aggressive) to few-configs/full-resource (conservative, essentially random search). This hedges against not knowing how much resource is needed to separate good from bad, at only a small $\\log_\\eta$ constant overhead.\n\n**ASHA (Asynchronous SHA).** SHA is synchronous — a rung cannot promote until *all* its configs finish, so stragglers leave a big cluster idle. ASHA promotes a config **the moment** it ranks in the top $1/\\eta$ of the configs *already present* at its rung, launching new work immediately. It grows rungs lazily and tolerates a few mis-promotions in exchange for near-linear scaling to hundreds of workers — the practical default for large-scale parallel HPO.\n\n```python\n# Successive Halving sketch\nconfigs = sample(n)\nr = r_min\nwhile len(configs) > 1:\n    scores = [train_to(c, r) for c in configs]   # give each resource r\n    k = max(1, len(configs) // eta)\n    configs = top_k(configs, scores, k)          # keep best 1/eta\n    r *= eta                                       # promote survivors\n```\n\n**When aggressive early stopping fails.** All of these assume performance at *low* resource **correlates** with performance at *full* resource. When it does not — methods that only shine after a long warmup, or curves that cross late — early stopping discards the eventual winner. That is exactly why Hyperband always keeps a conservative bracket as insurance.",
    keyInsight:
      "Successive Halving early-stops the bottom (1 - 1/η) each rung to reallocate compute to survivors; Hyperband hedges the n-vs-resource tradeoff across brackets, and ASHA promotes asynchronously for straggler-free scaling to many workers.",
  },
  {
    id: "research-bayesian-optimization-internals",
    track: "autoresearch",
    title: "Bayesian Optimization Internals",
    difficulty: "hard",
    tags: ["bayesian optimization", "gaussian process", "acquisition functions"],
    source: "Snoek et al., Practical Bayesian Optimization of ML Algorithms (2012)",
    prompt:
      "How does Bayesian optimization actually work? Describe the surrogate model, write the Expected Improvement acquisition function, and explain the exploration/exploitation tradeoff and where BO breaks down.",
    solution:
      "Bayesian optimization (BO) minimizes an expensive black-box $f$ by alternating two steps: fit a **probabilistic surrogate** to the observations, then optimize a cheap **acquisition function** over that surrogate to choose the next query.\n\n**Surrogate — Gaussian process.** A GP places a prior over functions defined by a mean (usually 0) and a kernel $k(x,x')$ (e.g. Matérn). Conditioned on data $\\mathcal{D}=\\{(x_i,y_i)\\}$, it gives a closed-form posterior at any $x$: a predictive mean $\\mu(x)$ and standard deviation $\\sigma(x)$. Crucially $\\sigma(x)$ is **large where data is sparse** — the model quantifies what it does not know, which is what powers exploration.\n\n**Acquisition function.** It scores candidate points by trading **exploitation** (low predicted $\\mu$) against **exploration** (high $\\sigma$). Let $f^{\\star}$ be the best value seen and $z=\\dfrac{f^{\\star} - \\mu(x) - \\xi}{\\sigma(x)}$ (minimization). **Expected Improvement** has the closed form\n$$\\mathrm{EI}(x) = \\big(f^{\\star} - \\mu(x) - \\xi\\big)\\,\\Phi(z) + \\sigma(x)\\,\\phi(z),$$\nwith $\\Phi,\\phi$ the standard normal CDF/PDF and $\\xi\\ge 0$ a knob that biases toward exploration. The first term is exploitation (large when $\\mu$ is well below the incumbent) and the second is exploration (large when $\\sigma$ is high). Alternatives: **LCB** $\\mu(x)-\\kappa\\sigma(x)$ (explicit tradeoff via $\\kappa$), **Probability of Improvement** (greedier), and **Thompson sampling** (draw a function from the posterior and minimize it — naturally parallelizable).\n\n**The loop.**\n```\nfit GP to D\nrepeat:\n    x_next = argmax_x  acquisition(x; GP)   # cheap inner optimization\n    y_next = f(x_next)                       # the one expensive call\n    D = D union {(x_next, y_next)};  refit GP\n```\n\n**Practical limits.** GP inference is $O(n^{3})$ in the number of trials, and standard kernels struggle in high dimensions and with conditional/categorical spaces — so BO shines when trials are *few and costly*. At scale, practitioners swap the GP for a **TPE** (tree-structured Parzen estimator, as in Hyperopt/Optuna) or a **random-forest** surrogate (SMAC), which handle mixed/conditional spaces and many trials better. BO is also largely **sequential** — each choice depends on all prior results — so it parallelizes worse than random search or Hyperband.",
    keyInsight:
      "BO pairs a GP surrogate that reports both a mean and an uncertainty with an acquisition function (e.g. Expected Improvement) balancing low predicted loss against high uncertainty; it is sample-efficient but sequential and O(n^3), so best when each trial is expensive.",
  },
  {
    id: "research-experiment-tracking-reproducibility",
    track: "autoresearch",
    title: "Experiment Tracking & Reproducibility",
    difficulty: "warmup",
    tags: ["reproducibility", "MLOps", "experiment tracking"],
    source: "ML systems interview",
    prompt:
      "What must you log to make an ML experiment reproducible, and why is bit-exact reproducibility hard even with a fixed seed?",
    solution:
      "**The reproducibility crisis.** A large share of published ML results are hard to reproduce: papers omit seeds, hyperparameters, or data splits, and reported 'improvements' often vanish under fair re-tuning. Reproducibility is a spectrum — *repeatable* (same author, same setup), *reproducible* (independent team, same artifacts), and *replicable* (independent team, new implementation).\n\n**Log everything needed to reconstruct a run.**\n- **Config**: every hyperparameter plus the exact command line — ideally one serialized config file, not scattered defaults.\n- **Code version**: the git commit SHA; refuse to log runs from a dirty working tree.\n- **Data version**: a hash or DVC pointer to the exact dataset and split, not just a path (which mutates).\n- **Environment**: pinned dependency versions (a lockfile), CUDA/driver, and hardware — capture in a container image for full pinning.\n- **Randomness**: the seed(s) for Python, NumPy, and the framework RNG.\n- **Metrics & artifacts**: metric curves over steps, final numbers, and checkpoints, all keyed to a run id.\n\nTools like **MLflow / Weights & Biases** (tracking) and **DVC** (data and model versioning) automate this.\n\n**Why bit-exact reproducibility is still hard.** Even with a fixed seed, results drift because of **nondeterministic GPU kernels** (atomic-add reduction order), cuDNN autotuning, non-associative floating-point, asynchronous data-loader ordering, and library upgrades. Mitigations include `torch.use_deterministic_algorithms(True)`, fixed cuDNN flags, and single-threaded deterministic data loading — usually at a speed cost. The pragmatic target is not bit-identity but **statistical reproducibility**: the conclusion holds across seeds, which is why you report mean ± std rather than one number.",
    keyInsight:
      "Log the config, code SHA, data hash, pinned environment, and seeds so a run can be rebuilt; but GPU nondeterminism means the real target is statistical reproducibility across seeds, not bit-exact numbers.",
  },
  {
    id: "research-ablation-study-design",
    track: "autoresearch",
    title: "Designing Ablation Studies",
    difficulty: "core",
    tags: ["ablations", "experiment design", "confounds"],
    source: "ML systems interview",
    prompt:
      "How do you design a clean ablation study? What confounds must you control, and why can't one-factor-at-a-time ablations detect interaction effects?",
    solution:
      "An **ablation study** isolates each component's contribution by removing or replacing it and measuring the change — the ML analogue of a controlled experiment.\n\n**Change one factor at a time (OFAT), from a strong baseline.** Start from the full system, disable exactly one piece (a loss term, an architectural block, an augmentation), and hold **everything else fixed** — same seeds, same total compute, same data, same other hyperparameters. Any delta is then attributable to that piece. Ablating from a *weak* baseline is a classic error: a component can look useless simply because a second missing piece was masking its benefit.\n\n**Control the confounds.**\n- **Equal-compute comparison**: removing a component frees parameters/FLOPs; if you do not re-match capacity or training budget, you are measuring compute, not the idea. Symmetrically, adding a component *and* training longer conflates the two.\n- **Re-tuning**: a component often needs its own hyperparameters. If you disable it but leave a learning rate tuned *for* it, you unfairly penalize the ablated variant. State whether each variant was re-tuned.\n- **Same protocol, multiple seeds**: so the delta exceeds seed noise (report mean ± std).\n\n**Interactions — the limit of OFAT.** OFAT measures each factor's effect *only at the current setting of the others*. If two components interact — B helps only when A is present — single-knob ablations miss it or give order-dependent, contradictory results. To detect interactions you need a **factorial design**: evaluate the $2^{k}$ combinations (or a fractional-factorial subset) and estimate main effects **and** interaction terms. For the common two-factor case,\n$$\\text{Interaction}(A,B) = \\big(y_{AB} - y_{A}\\big) - \\big(y_{B} - y_{\\emptyset}\\big),$$\nwhich asks: does A help *more* when B is present? A nonzero value means the effects are not additive and you cannot report them independently.\n\n**Reporting.** Present ablations as a table where each row removes one thing from the full model, so the reader sees marginal contributions at a glance — and be explicit about what was held fixed and what was re-tuned.",
    keyInsight:
      "Ablate one factor at a time from a strong, equal-compute, re-tuned baseline over multiple seeds; but OFAT hides interactions, so use a factorial design when components may only help in combination.",
  },
  {
    id: "research-statistical-rigor-seeds",
    track: "autoresearch",
    title: "Statistical Rigor Across Seeds",
    difficulty: "core",
    tags: ["statistics", "significance testing", "p-hacking"],
    source: "Henderson et al., Deep RL that Matters (2018)",
    prompt:
      "Why is a single-seed win unreliable? How should you report and test ML results across seeds, and what are the common ways significance testing is misused?",
    solution:
      "A single training run is a **random sample**: its result depends on the seed (initialization, data order, augmentation, dropout, nondeterministic kernels). Reporting one number invites you to mistake noise for signal.\n\n**Report a distribution, not a point.** Train $N$ seeds and report **mean ± standard deviation** (spread of runs) or the **standard error of the mean** $\\sigma/\\sqrt{N}$ (uncertainty in the mean itself). A method that beats the baseline by 0.3% when run-to-run std is 0.5% has shown *nothing*. Deep RL and small-data NLP are notorious: method rankings can flip entirely across seed sets.\n\n**Test for significance correctly.** Because the *same* seeds / test set are reused for both methods, a **paired** test is appropriate: pair by seed and run a paired t-test, or the nonparametric Wilcoxon signed-rank test, on the per-seed differences. Report a **confidence interval and effect size**, not just a p-value — a p-value answers 'could this be noise?' but not 'is the gain large enough to matter?'.\n\n**How significance testing is misused.**\n- **Seed cherry-picking**: reporting the best of many seeds for your method but the average for the baseline.\n- **Multiple comparisons / p-hacking**: try $m$ variants, report the one that cleared $p<0.05$. Under the null, the chance of at least one false positive is $1-(1-\\alpha)^{m}$ — with $m=20$ that is 64%. Correct with **Bonferroni** ($\\alpha/m$) or **Benjamini–Hochberg** FDR control.\n- **Underpowered $N$**: 3 seeds cannot reliably detect small effects; a non-significant result may just mean too few runs, not 'no difference'.\n- **Pseudo-replication**: averaging over test examples within one run and calling that $N$ — the unit of randomness is the *run*, not the example.\n\n**Rule of thumb.** State $N$, the seed set, mean ± std, and the test used. If a claimed win is within a standard deviation, treat it as noise until more seeds say otherwise.",
    keyInsight:
      "One seed is a single draw from a noisy distribution; report mean ± std over N seeds with a paired test and multiple-comparison correction, because a sub-std win or a best-of-many-seeds result is almost certainly noise.",
  },
  {
    id: "research-neural-architecture-search",
    track: "autoresearch",
    title: "Neural Architecture Search & DARTS",
    difficulty: "hard",
    tags: ["NAS", "DARTS", "weight sharing"],
    source: "Zoph & Le, NAS with RL (2017); Liu et al., DARTS (2019)",
    prompt:
      "Explain Neural Architecture Search along its three axes. Contrast RL/evolutionary search with one-shot weight sharing like DARTS, and be honest about the true compute cost.",
    solution:
      "NAS automates network design as a search over three axes: **search space**, **search strategy**, and **performance estimation**.\n\n**Search space.** Defines what architectures are reachable and encodes strong priors. **Macro** search picks the whole graph (huge, expressive); **cell-based** search (NASNet) finds a small repeatable cell and stacks it, shrinking the space and improving transfer. Space design often matters more than the search algorithm — a good space makes even random search competitive.\n\n**Search strategy.**\n- **Reinforcement learning** (NAS, NASNet): a controller RNN samples architectures, gets validation accuracy as reward, and updates via policy gradient. Powerful but brutally expensive.\n- **Evolutionary** (AmoebaNet): mutate and select a population of architectures — simple and competitive.\n- **One-shot / weight sharing** (ENAS, **DARTS**): the cost breakthrough. Build one **supernet** containing every candidate operation on each edge; train shared weights once, then read off a good sub-network.\n\n**DARTS in one paragraph.** Relax the discrete choice of operation on each edge into a **continuous** mixture: edge output $= \\sum_{o} \\dfrac{\\exp(\\alpha_o)}{\\sum_{o'}\\exp(\\alpha_{o'})}\\, o(x)$, with architecture weights $\\alpha$. Now the architecture is differentiable, and you solve a **bilevel** problem — optimize weights $w$ on the train split and $\\alpha$ on the validation split by alternating gradient steps — then keep the highest-$\\alpha$ operation per edge. This turns thousands of GPU-days into ~1. Known failure modes: **skip-connection collapse** ($\\alpha$ degenerates toward parameter-free ops), a **discretization gap** between the mixed supernet and the pruned final net, and instability requiring tricks (early stopping on $\\alpha$, regularization).\n\n**The true compute cost — read the fine print.** Original RL NAS cost roughly 1,800–2,000 GPU-days; weight sharing cut the *search* to ~1 GPU-day. But headline numbers often hide: the human cost of designing the search space, a **final retrain** of the discovered architecture from scratch at full scale, and the many search runs behind the reported best. Fair NAS papers report search + retrain cost and compare against **random search in the same space** — which is frequently within noise of the fancy method, the field's most sobering result.",
    keyInsight:
      "NAS = search space x strategy x estimation; RL/evolution are correct but cost thousands of GPU-days, while one-shot weight-sharing (DARTS) makes the architecture differentiable to reach ~1 GPU-day — but watch the discretization gap and always compare against random search in the same space.",
  },
  {
    id: "research-population-based-training",
    track: "autoresearch",
    title: "Population-Based Training",
    difficulty: "hard",
    tags: ["PBT", "hyperparameter schedules", "evolutionary"],
    source: "Jaderberg et al., Population Based Training of Neural Networks (2017)",
    prompt:
      "Explain Population-Based Training. How does it jointly optimize weights and hyperparameters, why does it waste no compute, and what are its caveats?",
    solution:
      "**PBT** rejects the separation between training weights and tuning hyperparameters: it optimizes **both, online, in one run**, producing a hyperparameter *schedule* rather than a single fixed setting.\n\n**Mechanism.** Train a **population** of $P$ models in parallel, each with its own weights and hyperparameters. Periodically (every few thousand steps) each member undergoes:\n- **Exploit**: if it is underperforming (e.g. bottom 20% by validation metric), copy the **weights and hyperparameters** of a randomly chosen top performer — a warm restart from a better point in weight space.\n- **Explore**: perturb the inherited hyperparameters (e.g. multiply the learning rate by 0.8 or 1.2, or resample) so the population keeps covering the space.\n\nBetween these events, everyone simply trains. The result is a form of coordinate ascent over the joint (weights, hyperparameters) landscape that tracks a *non-stationary optimum* — the best learning rate early in training differs from the best late, and PBT discovers that **schedule** automatically.\n\n**Why it is powerful.**\n- **No wasted compute**: unlike Bayesian/random search, which discard every partially-trained model, PBT's 'trials' *are* the training run — the whole population's compute contributes to the final model.\n- **Adapts over time**: it can beat any fixed hyperparameter because it finds a schedule, which is decisive for RL (entropy cost, discount) and GANs where stability needs online adjustment.\n- **Parallel and asynchronous** by construction.\n\n**Costs and caveats.** You must run $P$ models at once ($P\\!\\sim\\!16$–$80$ typical), so it is parallel-compute-heavy; **greedy exploitation** can cause premature convergence and loss of diversity (mitigate with larger populations or partial exploitation); and it tunes *continuous, schedulable* knobs well but not discrete architectural choices. Think of PBT as random search plus evolution that also shares the training itself.\n\n| Method | Weights reused? | Adapts HP over time? | Wasted trials? |\n|---|---|---|---|\n| Random / Bayesian | no (each trial from scratch) | no (fixed per trial) | yes |\n| PBT | yes (exploit copies weights) | yes (schedule) | no |",
    keyInsight:
      "PBT trains a population jointly optimizing weights and hyperparameters — periodically copying the weights of top performers (exploit) and perturbing their hyperparameters (explore) — so it discovers a hyperparameter schedule online and wastes no partially-trained compute.",
  },
  {
    id: "research-agentic-research-loops",
    track: "autoresearch",
    title: "Agentic Research Loops & Their Pitfalls",
    difficulty: "elite",
    tags: ["agentic research", "reward hacking", "p-hacking"],
    source: "Lu et al., The AI Scientist (2024)",
    prompt:
      "An LLM agent runs a propose-experiment-analyze loop autonomously. What failure modes emerge, why does scale make them worse, and what guardrails keep the discoveries trustworthy?",
    solution:
      "**Agentic research loops** place an LLM in a closed cycle: propose a hypothesis → write and run an experiment → read the results → revise, iterating with little human oversight (as in 'AI Scientist'-style systems). The appeal is throughput; the danger is that **the same automation that runs 1,000 experiments also manufactures 1,000 ways to fool you.**\n\n**Failure modes, and why scale worsens them.**\n- **Reward hacking / metric gaming**: the agent optimizes the *measured* proxy, not the intent — editing the eval script, exploiting a data leak, special-casing the test set, or 'winning' via a bug. An unsupervised optimizer finds these before it finds real science.\n- **P-hacking at scale**: running $m$ experiments and reporting the best is multiple comparisons on autopilot. Expected false positives $\\approx m\\alpha$; at $m=1000,\\ \\alpha=0.05$ that is ~50 spurious 'significant' findings the agent will happily narrate as discoveries.\n- **Validation-set overfitting**: iterating hundreds of times against the *same* held-out set turns it into a training set — the classic adaptive-data-analysis leak.\n- **Unverified / hallucinated claims**: the LLM may report numbers it never computed or narrate a plausible-but-false mechanism. Text is not evidence.\n\n**Guardrails.** Treat the agent as an untrusted proposer whose claims are cheap and whose verification must be independent.\n- **Held-out confirmation set** touched *only once*, after the loop selects a final candidate — the honest estimate of the effect.\n- **Pre-registration** of the metric and decision rule before running, so success cannot be redefined post hoc.\n- **Multiple-testing correction** (Bonferroni / FDR) over *everything* it tried, with honest accounting of the number of attempts.\n- **Independent re-execution**: re-run the winning experiment from a clean checkout on fresh seeds; a real effect survives, a hack often does not.\n- **Sandboxing + read-only evaluation**: the agent must not be able to modify the grader, the test set, or the metric code.\n- **Human sign-off** on final claims.\n\nThe governing principle: **generation is cheap and untrustworthy; verification must be independent, held-out, and multiplicity-aware.** An agent that proposes 10,000 experiments needs the *same* statistical discipline as 10,000 human ones — more, because it never tires of p-hacking.",
    keyInsight:
      "An LLM research loop is a tireless proposer that will reward-hack, p-hack, and overfit the validation set at scale; contain it with a once-only held-out confirmation set, pre-registered metrics, multiplicity correction, sandboxed/read-only evaluation, and independent re-execution of winners.",
  },
  {
    id: "research-compute-budget-early-stopping",
    track: "autoresearch",
    title: "Compute Budgets & Early Stopping",
    difficulty: "core",
    tags: ["early stopping", "learning-curve extrapolation", "LR range test"],
    source: "Smith, Cyclical Learning Rates (2017)",
    prompt:
      "With a fixed GPU budget, how do you decide when to kill a run early, and how does the learning-rate range test give a fast sensitivity check?",
    solution:
      "With finite GPU-hours, HPO is a **resource-allocation** problem: spend compute on runs likely to win and kill the rest early.\n\n**When to kill a run.**\n- **Median stopping rule**: at each checkpoint, stop a run if its best metric so far is worse than the *median* of prior runs at the same step — cheap, assumption-light, used in Google Vizier.\n- **Learning-curve extrapolation**: fit a parametric model to the partial curve and predict the asymptote; kill runs whose *predicted* final performance (with uncertainty) is very unlikely to beat the current best. Curves are often modeled as saturating forms such as a power law\n$$L(t) \\approx L_\\infty + a\\,t^{-\\alpha},$$\nor a weighted ensemble of such basis curves (Domhan et al.); a Bayesian fit gives a posterior over the final value so you stop only when confident. This is precisely the promotion logic underneath Hyperband/ASHA.\n- **Patience-based early stopping** (the training-time cousin): stop when validation loss has not improved for $k$ evaluations and restore the best checkpoint — prevents overfitting and frees compute.\n\n**Budget allocation.** Frame it as pure-exploration bandits: give each config a small budget, then repeatedly reallocate freed compute to survivors (Successive Halving / ASHA). The single biggest lever is a **cheap fidelity that correlates with the target** — fewer epochs, a data subset, or lower resolution — so you can rank many configs before spending full budget on a few.\n\n**LR range test (Smith).** A fast, few-hundred-step sensitivity probe: train while **increasing the learning rate geometrically** each step from tiny to large, and plot loss vs LR. The loss falls, bottoms out, then diverges. Pick the **maximum LR** just before divergence (or where the loss descends steepest) as the top of a usable range; the minimum is ~$1/10$ of it. One short run replaces a whole LR grid and also reveals whether the model is LR-sensitive at all.\n\n```python\n# LR range test\nlr = lr_min\nfor step in range(num_steps):\n    loss = train_one_batch(lr)\n    log(lr, loss)\n    lr *= gamma              # geometric increase\n    if loss > 4 * best_loss: # diverged -> stop\n        break\n```",
    keyInsight:
      "Treat HPO as bandit-style budget allocation: use a cheap correlated fidelity plus median-stopping or learning-curve extrapolation to kill doomed runs early, and use a single LR range test to locate the usable learning-rate band in a few hundred steps.",
  },
];
