import type { Problem } from "../types";

export const dataManagement: Problem[] = [
  {
    id: "data-minhash-lsh-dedup",
    track: "data",
    title: "Near-Duplicate Deduplication at Scale (MinHash + LSH)",
    difficulty: "hard",
    tags: ["deduplication", "MinHash", "LSH", "pretraining"],
    source: "Deduplicating Training Data Makes Language Models Better (Lee et al., 2021)",
    prompt:
      "You are assembling a pretraining corpus of billions of web documents. Exact-hash deduplication only removes byte-identical copies. Why is that insufficient, and how would you find and remove **near-duplicates** at scale? Explain MinHash + LSH, and contrast document-level with sequence-level deduplication.",
    solution:
      "**Why exact dedup is not enough.** Byte-identical hashing (SHA-256) catches only perfect copies. The web is full of *near*-duplicates: the same article re-hosted with a different ad, header, timestamp, or URL; templated boilerplate pages; SEO spam that permutes a few words. Left in, these inflate the effective number of epochs on repeated content, which drives **memorization / verbatim regurgitation**, wastes compute, and worsens downstream quality (Lee et al., *Deduplicating Training Data Makes Language Models Better*, 2021). They also silently leak across train/test splits.\n\n**The similarity we want.** Represent a document as the set of its $n$-gram **shingles** $A$. Near-duplicates have high **Jaccard similarity**\n$$J(A,B)=\\frac{|A\\cap B|}{|A\\cup B|}.$$\nWe want all pairs with $J\\ge$ some threshold (e.g. $0.8$). Comparing all pairs is $O(N^2)$ — hopeless for billions of documents.\n\n**MinHash.** For a random hash $h$, define $\\min h(A)=\\min_{x\\in A}h(x)$. The key identity is\n$$\\Pr[\\min h(A)=\\min h(B)] = J(A,B).$$\nWith $k$ independent hashes, a document's **signature** is the vector of $k$ minima; the fraction of matching positions is an unbiased estimate of $J$ with standard error $\\sqrt{J(1-J)/k}$. This compresses each document to a fixed-length $k$ signature.\n\n**LSH banding.** To avoid comparing all signature pairs, split the length-$k$ signature into $b$ **bands** of $r$ rows ($k=b\\cdot r$). Two docs are a **candidate pair** if they match on *all* $r$ rows of *at least one* band. For a pair with true similarity $s$, the probability of becoming a candidate is\n$$P(s)=1-\\bigl(1-s^{\\,r}\\bigr)^{b},$$\nan S-curve with a sharp knee near $(1/b)^{1/r}$. Tune $(b,r)$ to place the knee at your target: larger $r$ is a stricter AND within a band, larger $b$ is more OR across bands.\n\n| target ~threshold | $k$ | $b$ | $r$ |\n| --- | --- | --- | --- |\n| ~0.8 | 90 | 9 | 10 |\n| ~0.9 | 160 | 8 | 20 |\n\nCandidates are then verified by exact Jaccard if desired, and near-dup clusters collapsed to one representative. The whole pipeline is $O(N)$ with hashing + bucketing and parallelizes trivially (MapReduce/Spark).\n\n**Document- vs sequence-level dedup.**\n- **Document-level** (MinHash/LSH above) removes whole documents that are globally similar — ideal for killing re-hosted pages and template spam.\n- **Sequence-level / exact-substring** dedup (suffix arrays or Bloom-filtered $n$-gram matching, the *ExactSubstr* method in Lee et al.) removes long *repeated spans* (say $\\ge 50$ tokens) even when the surrounding documents differ. This most directly cuts **verbatim memorization**, because it targets the exact duplicated strings a model would otherwise over-see.\n\nIn practice you use both: MinHash for global redundancy, exact-substring for local repetition. Deduplication reliably improves perplexity-per-token, reduces memorization, and removes accidental train/test overlap.",
    keyInsight:
      "MinHash turns Jaccard similarity into cheap signature matching and LSH banding turns near-dup search into an O(N) bucketing problem; combine document-level (MinHash) with sequence-level (exact-substring) dedup to cut both global redundancy and verbatim memorization.",
  },
  {
    id: "data-quality-filtering",
    track: "data",
    title: "Data Quality Filtering for LLM Pretraining",
    difficulty: "core",
    tags: ["data quality", "filtering", "Common Crawl"],
    source: "Scaling Language Models: Gopher (Rae et al., 2021) / C4 (Raffel et al., 2020)",
    prompt:
      "How do you turn a raw web scrape (e.g. Common Crawl) into a high-quality LLM pretraining corpus? Describe heuristic rules, classifier-based filters, and perplexity filtering, and their trade-offs.",
    solution:
      "A production pipeline chains cheap-to-expensive filters, typically **language ID -> heuristic rules -> dedup -> quality classifier / perplexity -> decontamination**.\n\n**1. Language identification.** A fastText/CLD3 classifier tags each document's language; keep target languages and drop low-confidence gibberish. Do this early — it is cheap and prunes a lot.\n\n**2. Heuristic quality rules (Gopher / C4 / MassiveText).** Hand-written signals that flag junk without a model:\n\n| signal | typical rule |\n| --- | --- |\n| document length | drop if < 50 or > 100k words |\n| mean word length | keep between 3 and 10 chars |\n| symbol-to-word ratio | drop if too many hashes / ellipses |\n| bullet / ellipsis lines | drop if most lines are bullets |\n| fraction of alpha words | require most tokens contain a letter |\n| stop-word presence | a real English doc contains some of {the, be, to, of, and} |\n| duplicate lines / $n$-grams | drop docs with heavy internal repetition |\n| boilerplate / blocklist | drop 'lorem ipsum', cookie/JS notices, bad-word/URL lists |\n\nC4 additionally keeps only lines ending in terminal punctuation, drops pages with fewer than 5 sentences, and strips lines containing 'javascript' or curly braces.\n\n**3. Classifier-based quality filter (GPT-3 style).** Train a light classifier (logistic regression / fastText) to separate a **high-quality reference** (Wikipedia, books, WebText = pages linked from Reddit) from random Common Crawl, then score every document. Keep by threshold, or stochastically via a Pareto draw so you do not fully collapse onto the reference distribution:\n```python\nkeep = np.random.pareto(alpha=9) > (1 - score)\n```\n**Risk:** it biases toward the reference distribution — it can filter out valid dialects, non-Western content, and technical text, reducing diversity.\n\n**4. Perplexity filtering (CCNet).** Train a small $n$-gram LM (e.g. KenLM) on a clean domain (Wikipedia) and score each document's perplexity; keep low-perplexity (in-distribution) text and bucket the rest into head/middle/tail. **Caveat:** it again favors text resembling the reference and can discard code, math, or rare-but-valuable domains.\n\n**Trade-offs.** Aggressive filtering raises average quality but **shrinks and narrows** the corpus; over-filtering hurts (you lose the long tail and diversity that pretraining needs). Recent work (RefinedWeb, FineWeb) shows that careful heuristics + strong dedup on pure web can rival curated corpora — so much of the gain comes from removing the *worst* content and duplicates, not from aggressively chasing a 'high-quality' reference.",
    keyInsight:
      "Chain cheap heuristics (Gopher/C4) and dedup first, then model-based quality/perplexity filters — but every classifier or perplexity filter biases toward its reference distribution, so the real win is removing junk and duplicates without collapsing diversity.",
  },
  {
    id: "data-doremi-mixture",
    track: "data",
    title: "Domain Re-Weighting of the Data Mixture (DoReMi)",
    difficulty: "elite",
    tags: ["data mixture", "domain weighting", "DoReMi", "group DRO"],
    source: "DoReMi: Optimizing Data Mixtures Speeds Up LM Pretraining (Xie et al., 2023)",
    prompt:
      "A pretraining corpus mixes domains (web, code, books, Wikipedia, arXiv, ...) with sampling weights. How do you set those weights? Contrast hand-tuning / upsampling with a learned method like DoReMi, and state the optimization it solves.",
    solution:
      "Let the mixture be a distribution $\\alpha=(\\alpha_1,\\dots,\\alpha_K)$ over $K$ domains — $\\alpha_i$ is the probability that a training token is drawn from domain $i$. These weights strongly affect downstream performance, and the design space is huge.\n\n**Baseline practice.**\n- **Proportional to tokens** lets the giant web domain dominate and starves small high-quality sources.\n- **Hand-tuned upsampling** (GPT-3, The Pile): repeat small high-quality domains (Wikipedia, books) for a few epochs and downweight noisy web. Constraint: too many repeats cause memorization — scaling studies (Muennighoff et al.) suggest up to ~4 epochs of repetition is roughly as good as fresh data, degrading after.\n- The weakness: tuning weights by training many large models and reading downstream scores is expensive and does not transfer cleanly across scales.\n\n**DoReMi (Xie et al., 2023) — Domain Reweighting with Minimax Optimization.** Learn the weights cheaply with small proxy models, then reuse them for the big run:\n1. Train a small **reference** model $\\theta_{\\text{ref}}$ on baseline weights.\n2. Train a small **proxy** model with **group DRO**, tuning domain weights to minimize the *worst-case excess loss* relative to the reference:\n$$\\min_{\\theta}\\ \\max_{\\alpha\\in\\Delta^{K}}\\ \\sum_{i=1}^{K}\\alpha_i\\,\\underbrace{\\Bigl(\\tfrac{1}{|D_i|}\\!\\sum_{x\\in D_i}\\ell_\\theta(x)-\\ell_{\\theta_{\\text{ref}}}(x)\\Bigr)}_{\\text{excess loss on domain }i}.$$\n3. Use the **time-averaged** domain weights $\\bar\\alpha$ to train the large model.\n\n**Why excess loss, not raw loss?** Some domains have high but *irreducible* entropy (their loss floor is high no matter what). Weighting by raw loss would chase that noise. Excess loss = current loss minus the reference's loss measures **remaining learnable headroom**, so weight flows to domains where the model can still improve.\n\n**The online algorithm** alternates SGD on $\\theta$ with **exponentiated-gradient** ascent on $\\alpha$: on each step, upweight domains with high excess loss,\n$$\\alpha_i \\leftarrow \\alpha_i\\,\\exp\\!\\bigl(\\eta\\cdot \\text{excessloss}_i\\bigr),\\qquad \\alpha\\leftarrow \\alpha/\\textstyle\\sum_j\\alpha_j,$$\nkeeping $\\alpha$ on the simplex $\\Delta^{K}$. The final weights are the running average of the $\\alpha_t$.\n\n**Result.** With only small proxy/reference models and *no knowledge of downstream tasks*, DoReMi's learned weights improved average downstream accuracy and reached the baseline accuracy about $2.6\\times$ faster on The Pile. The broader lesson: set mixture weights by *where reducible loss lives*, and validate them at small scale before committing the expensive run.",
    keyInsight:
      "Set domain weights by learnable headroom, not raw loss: DoReMi runs group-DRO minimax (exponentiated-gradient on domain weights vs SGD on a small proxy) to upweight domains with high excess loss over a reference, then reuses those weights for the big model.",
  },
  {
    id: "data-tokenization-bpe-unigram",
    track: "data",
    title: "Tokenization Choices: BPE vs Unigram",
    difficulty: "core",
    tags: ["tokenization", "BPE", "SentencePiece", "multilingual"],
    source: "Subword Regularization / SentencePiece (Kudo, 2018)",
    prompt:
      "Compare BPE and unigram (SentencePiece) tokenization. How does vocabulary size trade off against sequence length, compute, and multilingual fairness?",
    solution:
      "Subword tokenization sits between characters (tiny vocab, very long sequences) and words (huge vocab, OOV problems), giving open-vocabulary coverage with reasonable sequence lengths.\n\n**BPE (byte-pair encoding).** Start from characters/bytes and greedily **merge the most frequent adjacent pair**, repeating until the vocab reaches the target size; encoding replays the learned merges in order (deterministic, greedy). **Byte-level BPE** (GPT-2) operates on raw UTF-8 bytes, so it has *no OOV* — any Unicode string is representable.\n\n**Unigram LM (Kudo; SentencePiece).** Start from a large candidate vocabulary and model a sequence's probability as a product of token unigram probabilities; use EM to iteratively **prune the tokens whose removal least hurts corpus likelihood**. At encode time pick the most probable segmentation (Viterbi), and optionally *sample* segmentations for **subword regularization**. It tends to yield more linguistically coherent, probabilistically-grounded pieces, whereas BPE is purely frequency-greedy.\n\n| | BPE | Unigram |\n| --- | --- | --- |\n| build | bottom-up merges | top-down pruning (EM) |\n| encode | replay merges (greedy) | Viterbi (probabilistic) |\n| regularization | BPE-dropout | native sampling |\n| tends to | frequent substrings | likelihood-optimal pieces |\n\n**Vocabulary size trade-offs.**\n- **Larger vocab -> shorter sequences** (lower *fertility* = tokens/word). Since attention is $O(n^2)$ and the FFN $O(n)$ in sequence length $n$, fewer tokens mean less compute per document and more text per context window. But the embedding + output softmax matrices are $V\\times d$, so a large $V$ costs parameters and memory, and rare tokens get few updates (undertrained).\n- **Smaller vocab -> longer sequences**, more compute, but a denser per-token training signal.\n\n**Multilingual fairness.** A vocab trained mostly on English over-fragments other scripts (high fertility), so those languages spend **more tokens per sentence** — more compute, shorter effective context, and higher per-sentence API cost, all for identical content. Mitigations: train the tokenizer on a balanced multilingual mix, **temperature-sample** low-resource languages ($p_i \\propto p_i^{\\,\\gamma}$ with $\\gamma<1$ to boost rare languages), and increase vocab size. Beware pathologies too: undertrained 'glitch' tokens (e.g. *SolidGoldMagikarp*), digit splitting that hurts arithmetic, and whitespace handling that matters for code.",
    keyInsight:
      "BPE greedily merges frequent pairs while unigram prunes a big vocab by likelihood; vocab size trades sequence length/compute against embedding cost, and English-centric vocabularies quietly tax other languages via higher token fertility.",
  },
  {
    id: "data-splitting-leakage",
    track: "data",
    title: "Train/Val/Test Splitting and Leakage",
    difficulty: "core",
    tags: ["data splitting", "leakage", "temporal split", "cross-validation"],
    source: "ML systems interview",
    prompt:
      "How do you split data into train/validation/test for an honest generalization estimate? Cover temporal splits, grouped splits, cross-split deduplication, and common leakage traps.",
    solution:
      "The test set must be **representative of deployment** and **independent of training**. A random i.i.d. split is the default but is wrong whenever the data has temporal or grouping structure.\n\n**Temporal splits.** For anything that predicts the future — forecasting, recommenders, fraud, credit — split by **time**: train on the past, test on the future. A random shuffle lets the model 'see the future' (train on events after the test window), giving optimistic metrics that collapse in production. It also mirrors reality (you train once, then serve on later data). For tuning, use rolling/expanding-window CV and never shuffle across the time boundary.\n\n**Grouped splits.** When many rows share an entity — multiple visits per patient, several rows per user, augmentations of one image — **all rows of a group must land on the same side**. Otherwise near-identical siblings straddle the split and the model 'generalizes' by memorizing the group. Use `GroupKFold` / split on the entity ID.\n\n**Cross-split deduplication.** Even a correct random split leaks if the corpus contains duplicates or near-duplicates that fall on both sides. Deduplicate **across** splits (exact + MinHash near-dup) so the test set is genuinely held out. This is exactly the **train-test contamination** problem for LLM benchmarks.\n\n**Classic leakage traps.**\n- **Target leakage:** a feature computed using the label or post-outcome information (e.g. `account_closed_date` when predicting churn). Available at train time, absent at prediction time.\n- **Preprocessing leakage:** fitting a scaler, imputer, encoder, or feature selector on the *full* dataset before splitting. Fit only on train, then transform val/test.\n- **Using test for tuning:** the validation set is for model selection; the **test set is touched once**, at the end.\n\n**Estimation vs selection.** When you both tune and estimate, use **nested CV**: an inner loop for hyperparameters, an outer loop for the honest performance estimate — otherwise the reported number is optimistically biased by selection.",
    keyInsight:
      "Match the split to the data's structure — by time for forecasting, by group for repeated entities, and dedup across splits — while fitting all preprocessing on train only and spending the test set exactly once.",
  },
  {
    id: "data-synthetic-model-collapse",
    track: "data",
    title: "Synthetic Data, Distillation, and Model Collapse",
    difficulty: "hard",
    tags: ["synthetic data", "distillation", "model collapse", "Self-Instruct"],
    source: "The Curse of Recursion / AI Models Collapse (Shumailov et al., 2023-24)",
    prompt:
      "More and more training data is model-generated (Self-Instruct, distillation, synthetic augmentation). What are the benefits, what is **model collapse**, and how do you use synthetic data safely?",
    solution:
      "**Why synthetic data.** It scales cheaply and targets gaps: **Self-Instruct/Alpaca** bootstrap instruction-tuning data by prompting a model to generate instructions from a seed set, filtering, then fine-tuning; **distillation** transfers a strong teacher's behavior into a smaller student via generated completions or soft labels; synthetic data can cover rare cases, avoid private user data, and drive RLAIF / Constitutional AI.\n\n**Model collapse (Shumailov et al., 2023-24).** When models are trained recursively on their own (or other models') outputs, the learned distribution **progressively loses variance and tails**. *Early collapse*: low-probability events (the tails) disappear first because they are the least sampled. *Late collapse*: the distribution narrows toward a low-variance mode far from the truth. The mechanism is compounding error: each generation is fit to samples from the previous model, so finite-sampling noise, model bias, and limited expressivity accumulate; rare modes are undersampled and vanish. For a simple Gaussian re-estimated and resampled each generation, the estimated variance performs a shrinking random walk toward $0$.\n\n**The crucial fixes — do not replace, and ground the signal.**\n- **Keep real data in the loop.** Collapse is driven by *replacing* real data with synthetic each round. If you **accumulate** (append synthetic to a growing pool that retains the original human data), the degradation is largely averted — real anchors hold the tails in place.\n- **Verify/filter with a ground-truth signal.** Synthetic data is safe when correctness is *checkable*: unit tests for code, a solver/checker for math, game outcomes, or a reward model. Grounded filtering injects real information rather than recycling model bias.\n- **Distill from a *stronger* model, not from yourself.** Teacher -> student distillation is fine; naive self-training on your own errors is the dangerous case.\n- **Preserve diversity:** sample with temperature, dedup synthetic outputs, and monitor output-distribution statistics for narrowing.\n\n**Bottom line:** distillation from a better model, or synthetic data validated by an external verifier, is productive; recursive self-training that *replaces* real data with unfiltered generations narrows the distribution and collapses.",
    keyInsight:
      "Synthetic data is safe when it adds real signal — a stronger teacher or a ground-truth verifier — and when you accumulate rather than replace human data; unfiltered recursive self-training loses the tails first and collapses toward a low-variance mode.",
  },
  {
    id: "data-active-learning",
    track: "data",
    title: "Active Learning: Which Examples to Label Next",
    difficulty: "core",
    tags: ["active learning", "uncertainty sampling", "diversity", "data selection"],
    source: "Active Learning Literature Survey (Settles, 2009)",
    prompt:
      "You have a large unlabeled pool and a fixed labeling budget. Which examples do you send to annotators next? Contrast uncertainty and diversity sampling, and give their failure modes.",
    solution:
      "**Active learning** iterates: train on the current labeled set, score the unlabeled pool, query the most *informative* points, label, repeat — aiming to hit target accuracy with far fewer labels than random sampling.\n\n**Uncertainty sampling.** Label where the current model is least confident. Common scores:\n- **Least confidence:** $1-\\max_y p(y\\mid x)$.\n- **Margin:** $p(y_{(1)}\\mid x)-p(y_{(2)}\\mid x)$ (small margin = uncertain).\n- **Entropy:** $H(x)=-\\sum_y p(y\\mid x)\\log p(y\\mid x)$ (large = uncertain).\n\nCrucially, you want **epistemic** uncertainty (reducible, from model ignorance) not **aleatoric** uncertainty (irreducible label noise) — querying inherently-ambiguous points wastes budget. Bayesian proxies (MC-dropout, deep ensembles, BALD) isolate epistemic uncertainty better than a single softmax.\n\n**Failure mode of pure uncertainty:** in a batch it picks many *near-identical* points from the same uncertain region -> redundant labels; it is also sensitive to miscalibration and can chase outliers or mislabeled examples.\n\n**Diversity / representativeness sampling.** Choose a batch that *covers* the input space — clustering, **core-set / k-center greedy**, or determinantal point processes — so the batch is non-redundant and representative of the pool's density.\n\n**Hybrid batch-mode methods** combine both, which is what you actually need because retraining after every single label is too costly. **BADGE**, for instance, embeds each point by its loss-gradient (magnitude encodes uncertainty, direction encodes diversity) and runs k-means++ to pick a spread-out, high-magnitude batch.\n\n**Practical caveats.**\n- **Cold start:** you need a seed model before uncertainty is meaningful — start with a small random batch.\n- **Biased labeled set:** active learning deliberately samples non-i.i.d., so the *labeled* set is not a valid evaluation set — always keep a separate **randomly-sampled** held-out test set.\n- **Label noise & cost:** noisy or expensive-to-label points can dominate; cost-aware active learning weights informativeness by annotation cost.",
    keyInsight:
      "Uncertainty sampling targets where the model is unsure (prefer epistemic over aleatoric), but alone it picks redundant near-duplicates — so batch-mode active learning combines informativeness with diversity (core-set/BADGE), and you must keep a separate random test set.",
  },
  {
    id: "data-versioning-lineage",
    track: "data",
    title: "Data Versioning, Lineage, and Reproducibility",
    difficulty: "warmup",
    tags: ["versioning", "lineage", "reproducibility", "dataset cards"],
    source: "Datasheets for Datasets (Gebru et al., 2018)",
    prompt:
      "What does it take to make a training run reproducible from the data side? Discuss immutable snapshots, content-hash addressing, lineage, and dataset cards.",
    solution:
      "Reproducibility means pinning *everything* that affects the model: code (git SHA), config/hyperparameters, environment (container digest), RNG seeds, and — the hardest part — the **exact data**, which is large and mutable.\n\n**Immutable snapshots.** Never mutate a dataset in place. Each version is a new, write-once artifact; a movable pointer like `latest` may advance, but a given version never changes. This makes 'which data trained this model' answerable forever.\n\n**Content-hash addressing.** Address data by the hash of its bytes (like git): identical content -> identical hash, any change -> a new hash. This gives free deduplication of storage, integrity verification (detect silent corruption), and unambiguous references. Backing tools: **DVC**, Git-LFS, LakeFS, Delta/Iceberg time-travel, Hugging Face dataset revisions.\n\n**Lineage / provenance.** Track where each dataset came from and the transformations that produced it (source -> filter -> dedup -> tokenize), plus which data version trained which model. Lineage lets you reproduce a run, audit 'what is in this model', and do **targeted removal** (GDPR deletion requests, or recalling a contaminated/licensed source).\n\n**Dataset cards / datasheets** (Gebru et al., *Datasheets for Datasets*). Document motivation, composition, collection process, preprocessing, licensing/consent, known biases, and intended use — the dataset analogue of a **model card**. Essential for governance, licensing, and downstream users' informed consent.\n\n**DVC-style tracking in practice.** Small pointer files (content hash + remote URI) live in git next to the code; the heavy data sits in object storage; a `dvc.lock` / pipeline file records the transformation DAG so anyone can rebuild the exact artifacts. The payoff is statistically (often bit-for-bit) reproducible runs, auditability, safe rollback, and the ability to **bisect a regression to a specific data change**.",
    keyInsight:
      "Treat data like code: immutable, content-hash-addressed snapshots plus recorded lineage and a dataset card make a run reproducible, auditable, and safely rollback-able — and let you bisect regressions or honor targeted-deletion requests.",
  },
  {
    id: "data-streaming-shards",
    track: "data",
    title: "Streaming Sharded Datasets for Large-Scale Training",
    difficulty: "core",
    tags: ["streaming", "sharding", "WebDataset", "shuffle buffer"],
    source: "WebDataset / large-scale data loading",
    prompt:
      "Your dataset does not fit in RAM and you are training across many GPUs/workers. How do you stream sharded data with good shuffling, high throughput, and determinism? (WebDataset-style)",
    solution:
      "**Shard the data** into many medium files (e.g. tar archives of a few hundred MB — WebDataset; or TFRecord/Parquet). Streaming then does large **sequential** reads (friendly to object stores and spinning disks) instead of random per-sample seeks, which destroy throughput on remote storage.\n\n**Two-level shuffling.** A true global shuffle needs random access, which streaming gives up, so approximate it:\n1. **Shuffle the shard list** every epoch.\n2. **Shuffle buffer:** fill a buffer of $N$ samples, emit a random one, refill from the stream. Larger $N$ -> closer to a true shuffle but more RAM. This trades randomness for throughput; combined with shard shuffling and interleaving several open shards, it is close enough in practice.\n\n**Deterministic sharding across workers.** Every sample must be seen **exactly once per epoch**, with no overlap and no gaps. Partition shards by DDP `rank`/`world_size`, then again by DataLoader `worker_id`:\n```python\nshards_for_worker = shards[(rank * num_workers + worker_id)::(world_size * num_workers)]\n```\nSeed the shuffles with `(epoch, rank)` so runs are reproducible and resumable. Handle non-divisibility deliberately: **each rank must yield the same number of batches**, or a collective (all-reduce) will deadlock — so `drop_last` or pad/wrap consistently across ranks.\n\n**Throughput.** Prefetch and overlap I/O with compute, decode/decompress in worker processes, and run enough workers to saturate the GPU. For **mixture weighting**, interleave shards from multiple sources with the desired sampling probabilities.\n\n**Resumability.** Checkpoint the iterator state — current shard/offset and RNG state — so a restart neither repeats nor skips data. Getting this wrong silently biases the epoch.",
    keyInsight:
      "Shard for sequential I/O and approximate a global shuffle with shard-list shuffling plus a shuffle buffer; partition shards deterministically by (rank, worker) so every sample is seen once, keep per-rank batch counts equal to avoid DDP deadlock, and checkpoint iterator state for clean resumes.",
  },
  {
    id: "data-pii-decontamination",
    track: "data",
    title: "PII Removal and Benchmark Decontamination",
    difficulty: "core",
    tags: ["PII", "decontamination", "n-gram overlap", "privacy"],
    source: "Language Models are Few-Shot Learners: GPT-3 (Brown et al., 2020)",
    prompt:
      "Before training you must strip PII and remove overlap with evaluation benchmarks. How do you do each — and specifically, how does n-gram-overlap decontamination work?",
    solution:
      "**PII removal.** Detect and redact personal data — emails, phone numbers, SSNs, credit-card numbers, IPs, physical addresses, names. Techniques:\n- **Regex** for structured patterns (emails, phones, IPs; credit cards validated with a **Luhn** checksum to cut false positives).\n- **NER models** for contextual entities (person names, locations) that have no fixed pattern.\n- **Redact, do not delete:** replace with typed placeholders (`<EMAIL>`, `<PHONE>`) to preserve sentence structure.\n\nTrade-offs: high recall vs false positives (do not shred legitimate code, IDs, or public figures); you cannot hit 100%, so pair input-side scrubbing with **memorization audits** and output filters. Note the threat model: LLMs can memorize and **regurgitate rare PII** (Carlini et al., training-data extraction) — and deduplication reduces this because memorization scales with duplication.\n\n**Benchmark decontamination.** Eval sets (MMLU, GSM8K, HumanEval, ...) leak into web crawls; training on them inflates scores and invalidates evaluation. The standard detector is **n-gram overlap**:\n- Choose an $n$ (GPT-3 used 13-grams; other work uses 8-grams or an 8/50 rule). Build a hash set / **Bloom filter** of all $n$-grams from every eval example.\n- Stream the training corpus; flag a training passage that shares an $n$-gram with an eval example (or flag an eval example as contaminated if a high fraction of *its* $n$-grams appear in training). Remove the offending training spans/documents.\n- For exact long matches use suffix arrays / substring search; for fuzzy overlap use MinHash.\n\n**Report** the contamination rate and, like GPT-3/GPT-4, also publish scores on the **clean subset** (eval items with contamination removed).\n\n**Caveats.** Threshold choice matters: short $n$ over-flags common phrases; long $n$ misses paraphrases. **Paraphrased or translated** contamination slips past n-gram checks entirely — so rely additionally on **freshly-collected held-out benchmarks** and **canary strings** (unique markers inserted into a dataset so you can later test whether a model was trained on it).",
    keyInsight:
      "Strip PII with Luhn-checked regex plus NER and redact-not-delete, and decontaminate benchmarks by flagging training spans that share n-grams (via a Bloom filter of eval n-grams) — but paraphrased leakage evades n-gram checks, so also use canaries and fresh held-out evals.",
  },
  {
    id: "data-label-noise-imbalance",
    track: "data",
    title: "Label Noise and Class Imbalance from the Data Side",
    difficulty: "hard",
    tags: ["label noise", "confident learning", "imbalance", "resampling"],
    source: "Confident Learning: Estimating Uncertainty in Dataset Labels (Northcutt et al., 2021)",
    prompt:
      "Your labeled set has both noisy labels and severe class imbalance. From the data side, how do you *detect* mislabeled examples (confident learning) and *handle* imbalance (reweighting vs resampling)? What are the pitfalls, and in what order do you apply them?",
    solution:
      "**Detecting label errors — confident learning (Northcutt et al.; cleanlab).** Estimate the joint distribution of noisy (given) labels $\\tilde y$ and true labels $y^{*}$ from the model's **out-of-sample** predicted probabilities:\n1. Get cross-validated (out-of-fold) predicted probs $\\hat p(y\\mid x)$ for every example, so predictions are not memorized.\n2. For each class $j$, set a **per-class self-confidence threshold** $t_j=$ the average $\\hat p(y=j\\mid x)$ over examples *labeled* $j$.\n3. Count an example labeled $i$ as 'confidently really class $j$' when $\\hat p(y=j\\mid x)\\ge t_j$; accumulate the **confident joint** count matrix $C_{\\tilde y=i,\\;y^{*}=j}$.\n4. Normalize to the joint $Q_{i,j}$, then rank off-diagonal (label-error) examples by confidence and **prune or relabel** them.\n\nThe per-class thresholds (not one global cutoff) are what make it robust to **class imbalance** and to different noise rates per class.\n\n**Handling imbalance — two families.**\n- **Resampling:** oversample the minority (random duplication, or **SMOTE**, which synthesizes interpolated minority points) and/or undersample the majority. Pitfalls: random oversampling **overfits** duplicated points; SMOTE can fabricate unrealistic points in high-dimensional or overlapping regions and blur the decision boundary; undersampling **discards information**.\n- **Reweighting the loss:** weight classes inversely to frequency, use the **effective number of samples** $w_j\\propto (1-\\beta)/(1-\\beta^{\\,n_j})$ (Cui et al.), or **focal loss** to down-weight easy examples. No duplication, but extreme weights destabilize training and distort calibration.\n\n**Pitfalls that bite people.**\n- **Never resample the validation/test set.** Evaluate on the *true* distribution; balancing your metrics is a classic self-deception.\n- **Recalibrate afterward.** Resampling/reweighting shifts the effective class prior, so predicted probabilities become miscalibrated — correct the prior or re-fit calibration if you need real probabilities.\n- **Choose the right metric:** accuracy is meaningless under imbalance; use PR-AUC, F1, balanced accuracy, or a cost-sensitive metric tied to the business cost.\n- **Order matters:** oversampling *before* cleaning **amplifies** the mislabeled minority points.\n\n**Recommended order:** detect and clean noisy labels -> *then* address imbalance (reweight or resample the training split only) -> *then* pick the decision threshold from the cost trade-off, evaluating throughout on an untouched, true-distribution test set.",
    keyInsight:
      "Confident learning finds label errors via out-of-fold predicted probabilities and per-class confidence thresholds (robust to imbalance); then reweight or resample the training split only — never the test set — clean before balancing, and recalibrate since both shift the class prior.",
  },
];
